name: Update NCAAF Data

on:
  schedule:
    - cron: '0 7 * * *'
    - cron: '0 4 * * 0'    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: puntersloveit
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: update ncaa data
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: python scripts/update_ncaa_data.py
        
      - name: commit files
        run: |
          git config --local user.email "puntersloveit@github.com"
          git config --local user.name "puntersloveit"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated files" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
